/* No network calls, accounts, or runtime dependencies. */
'use strict';
const D=window.CPU_DATA,C=window.QuizCore,app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={cpu:'M7 7h10v10H7z M10 10h4v4h-4z M9 3v4m6-4v4M9 17v4m6-4v4M3 9h4m-4 6h4m10-6h4m-4 6h4',bolt:'m13 2-9 12h7l-1 8 10-12h-7z',book:'M4 4h6c2 0 2 2 2 2s0-2 2-2h6v15h-6c-2 0-2 2-2 2s0-2-2-2H4z M12 6v15',arrow:'M4 12h15m-6-6 6 6-6 6',back:'M20 12H5m6-6-6 6 6 6',clock:'M12 8v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',check:'m5 12 4 4 10-10',cross:'m6 6 12 12M6 18 18 6',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z m-4 9 3 3 5-6',info:'M12 11v6m0-10v.1 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',up:'M8 10 12 3c2 0 2 2 1 5h5c2 0 2 1 2 2l-2 9H8z M4 10h4v10H4z',down:'M8 14 12 21c2 0 2-2 1-5h5c2 0 2-1 2-2l-2-9H8z M4 4h4v10H4z',repeat:'M19 7a8 8 0 1 0 1 9 M19 3v5h-5',list:'M8 6h12M8 12h12M8 18h12M3 6h.1M3 12h.1M3 18h.1'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.book}"/></svg>`;
let storageOK=true;
const storage={read(k,fallback){try{const s=localStorage.getItem('cpu-v1-'+k);return s?JSON.parse(s):fallback;}catch{storageOK=false;return fallback;}},write(k,v){try{localStorage.setItem('cpu-v1-'+k,JSON.stringify(v));}catch{storageOK=false;}}};
let session=storage.read('session',null);if(!C.validSession(session,D.questions))session=null;
let history=storage.read('history',[]);history=Array.isArray(history)?history.filter(s=>C.validSession(s,D.questions)&&s.finishedAt).slice(0,100):[];
// Keep the answers actually shown in older attempts, including the unfinished test.
for(const s of [session,...history].filter(Boolean))for(const item of s.items){if(!item.optionsSnapshot){const q=D.questions.find(q=>q.id===item.questionId);item.optionsSnapshot=(q.legacyOptions||q.options).map(o=>({...o}));}}
const oddRecords=C.reviewRecords(D.issues),oddById=new Map(oddRecords.map(r=>[r.id,r]));
let oddSession=storage.read('odd-session',null);if(!C.validReviewSession(oddSession,D.issues))oddSession=null;
let ratings=storage.read('ratings',{});if(!ratings||typeof ratings!=='object'||Array.isArray(ratings))ratings={};
let screen=session&&!session.finishedAt?'quiz':'home',resultSession=null,bankTab='ready',query='',category='',page=0;
if(storage.read('active-mode','quiz')==='odd'&&oddSession&&!oddSession.finished)screen='odd';
const categories=[...new Set(D.questions.map(q=>q.category))];
const byId=new Map(D.questions.map(q=>[q.id,q])),sources=new Map(D.sources.map(s=>[s.id,s]));
const modeName=n=>n===10?'Szybki test':'Długi test';
const sourceText=q=>{const s=sources.get(q.sourceId);return `${s.file} · pytanie ${s.number}`;};
function btn(text,action,primary=false,extra=''){return `<button class="btn ${primary?'primary':''}" data-action="${action}" ${extra}>${text}</button>`;}
function shell(content,active='home'){
 app.innerHTML=`<div class="shell"><header class="topbar"><button class="brand" data-action="home" aria-label="Powtórka — strona główna"><span class="brand-mark">${icon('cpu')}</span>Powtórka<span>CPU</span></button><nav class="nav" aria-label="Menu główne">${[['home','Nauka'],['bank','Baza pytań'],['history','Historia']].map(([id,t])=>`<button data-action="${id}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${t}</button>`).join('')}</nav></header><main id="main" tabindex="-1">${!storageOK?'<div class="storage-warning" role="status">Przeglądarka blokuje zapis. Test działa, ale postęp nie będzie zachowany po zamknięciu.</div>':''}${content}</main><footer class="footer"><span>${icon('shield')} Działa lokalnie · Twoje postępy zostają w tej przeglądarce</span><span>Budowa i działanie procesora · ${D.meta.sourceFiles} materiałów źródłowych</span></footer></div>`;
}
function render(){
 if(screen==='odd')renderOdd();else if(screen==='quiz')renderQuiz();else if(screen==='results')renderResults();else if(screen==='mistakes')renderMistakes();else if(screen==='bank')renderBank();else if(screen==='history')renderHistory();else renderHome();
}
function go(next){screen=next;render();window.scrollTo({top:0});document.getElementById('main').focus({preventScroll:true});}
function renderHome(){
 const last=history[0];const best=history.length?Math.max(...history.map(s=>C.score(s,D.questions).percent)):null;
 shell(`<div class="animated"><div class="intro"><div class="eyebrow">Twoja przestrzeń do nauki</div><h1>Mała powtórka. Duży postęp.</h1><p>Budowa i działanie CPU. Wybierz test i sprawdź, ile już wiesz.</p></div>
 ${session&&!session.finishedAt?`<div class="notice resume">${icon('repeat')}<span>Masz rozpoczęty ${modeName(session.count).toLowerCase()} · pytanie ${session.index+1} z ${session.count}.</span>${btn('Kontynuuj '+icon('arrow'),'resume')}</div>`:''}
 <div class="home-grid">${[{n:10,title:'Szybki test',desc:'Krótka sesja na rozgrzewkę. Idealna na codzienną powtórkę.',time:'około 5 minut',icon:'bolt',tag:'NA DOBRY POCZĄTEK'},{n:40,title:'Długi test',desc:'Więcej pytań, pełniejszy obraz. Sprawdź swoją wiedzę przed sprawdzianem.',time:'około 20 minut',icon:'book',tag:'SPRAWDŹ SWOJĄ WIEDZĘ'}].map((m,i)=>`<article class="mode ${i===0?'featured':''}"><div class="mode-top"><div class="square-icon">${icon(m.icon)}</div><span class="badge">${m.tag}</span></div><h2>${m.title}</h2><p>${m.desc}</p><div class="mode-info"><span>${icon('list')}${m.n} losowych pytań</span><span>${icon('clock')}${m.time}</span></div>${btn('Rozpocznij test '+icon('arrow'),'start-'+m.n,i===0).replace('class="btn','class="full btn')}</article>`).join('')}</div>
 <article class="mode odd-mode"><div class="odd-intro"><span class="badge">ODDZIELNY TRYB · BEZ OCENY</span><h2>Dziwne pytania</h2><p>Niejasne pytania, dziwne sformułowania i błędne odpowiedzi z plików. Odkryj oryginalny zapis i zobacz, co wymaga poprawy.</p><span class="muted">10 losowych kart z ${oddRecords.length} spornych zapisów</span></div><div class="odd-actions">${btn('Rozpocznij przegląd '+icon('arrow'),'odd-start',true)}${oddSession&&!oddSession.finished?btn('Kontynuuj · '+(oddSession.index+1)+' / '+oddSession.ids.length,'odd-resume'):''}</div></article>
 <div class="stats"><div class="stat"><strong>${D.questions.length}</strong><span>pytań gotowych do nauki</span></div><div class="stat"><strong>${history.length}</strong><span>ukończonych testów</span></div><div class="stat"><strong>${best===null?'—':best+'%'}</strong><span>najlepszy wynik</span></div></div>
 <div class="section-title"><h2>Co dziś powtórzysz?</h2><button class="text-btn" data-action="bank">Przeglądaj bazę ${icon('arrow')}</button></div><div class="topic-list">${categories.map(c=>`<button class="chip" data-category="${esc(c)}">${esc(c)}<span>${D.questions.filter(q=>q.category===c).length}</span></button>`).join('')}</div>
 <div class="notice">${icon('info')}<span><b>${D.meta.reviewRecords} zapisów do wyjaśnienia.</b> Niejednoznaczne odpowiedzi są wyłączone z ocenianych testów. Możesz je przejrzeć w trybie „Dziwne pytania”.</span><button class="text-btn" data-action="issues">Zobacz uwagi ${icon('arrow')}</button></div>
 ${last?`<div class="section-title"><span class="muted">Ostatnio: ${modeName(last.count)} · ${C.score(last,D.questions).correct} / ${last.count}</span><button class="text-btn" data-result="${esc(last.id)}">Zobacz wynik ${icon('arrow')}</button></div>`:''}</div>`);
}
function start(count){session=C.createSession(D.questions,count);storage.write('session',session);storage.write('active-mode','quiz');go('quiz');}
function startOdd(){oddSession=C.createReviewSession(D.issues);storage.write('odd-session',oddSession);storage.write('active-mode','odd');go('odd');}
function renderOdd(){
 if(!oddSession){go('home');return;}
 const s=oddSession;
 if(s.finished){shell(`<div class="quiz-wrap animated"><section class="result-hero"><div class="eyebrow">Dziwne pytania · sesja zakończona</div><h1>Nie wszystko warto zapamiętać.</h1><p>Przejrzano ${s.ids.length} z ${s.ids.length} zapisów. Ten tryb nie wystawia oceny — odpowiedzi z plików mogą być błędne.</p><div class="review-list odd-summary">${s.ids.map(id=>{const r=oddById.get(id);return `<details><summary>${esc(r.question)} (${esc(r.author)})</summary><div class="detail-body"><p>Odpowiedź w pliku: ${esc(r.answer)}</p><p class="warning">${esc(r.reason)}</p></div></details>`;}).join('')}</div><div class="actions">${btn('Kolejne 10 kart','odd-start',true)}${btn('Menu główne','home')}</div></section></div>`);return;}
 const r=oddById.get(s.ids[s.index]),revealed=s.seen.includes(r.id);
 shell(`<div class="quiz-wrap animated"><div class="quiz-top"><button class="text-btn" data-action="home">${icon('back')} Zapisz i wróć</button><span>Dziwne pytania · ${s.index+1} z ${s.ids.length}</span></div><div class="progress-track" role="progressbar" aria-label="Przejrzane karty" aria-valuemin="0" aria-valuemax="${s.ids.length}" aria-valuenow="${s.seen.length}"><div class="progress-fill" style="width:${s.seen.length/s.ids.length*100}%"></div></div><section class="question-card odd-card"><div class="card-top"><span class="label">Dziwne pytania</span><span class="badge">ORYGINALNY ZAPIS</span></div><p class="warning">Nie ucz się tej odpowiedzi jako faktu. To niejasny, niepełny lub błędny zapis z materiałów.</p><h1 class="question-title">${esc(r.question)} (${esc(r.author)})</h1>${revealed?`<div class="answer-note questionable"><small>Odpowiedź w pliku — niezweryfikowana</small>${esc(r.answer)}</div><div class="issue-explanation" role="status"><h2>Co tu jest nie tak?</h2><p>${esc(r.reason)}</p></div><p class="source">${esc(r.file)} · pytanie ${r.number}</p>`:`<p class="muted">Zastanów się, co jest niejasne w pytaniu. Odkryj odpowiedź autora i sprawdź uwagę.</p>${btn('Pokaż odpowiedź i problem','odd-reveal',true)}`}</section><div class="quiz-bottom">${btn(icon('back')+' Wstecz','odd-previous',false,s.index===0?'disabled':'')}${btn((s.index===s.ids.length-1?'Zakończ sesję':'Następna karta')+' '+icon('arrow'),'odd-next',true,revealed?'':'disabled')}</div><p class="source">10 losowych zapisów ze ${oddRecords.length} · bez powtórzeń w sesji · bez punktacji</p></div>`);
}
function renderQuiz(){
 if(!session||session.finishedAt){go('home');return;}
 const item=session.items[session.index],original=byId.get(item.questionId),q={...original,options:item.optionsSnapshot||original.options},answered=session.items.filter(i=>i.selectedId!==null).length;
 shell(`<div class="quiz-wrap"><div class="quiz-top"><button class="text-btn" data-action="home">${icon('back')} Zapisz i wróć</button><span>${modeName(session.count)} <span aria-hidden="true"> / </span> ${session.index+1} z ${session.count}</span></div><div class="progress-track" role="progressbar" aria-label="Udzielone odpowiedzi" aria-valuemin="0" aria-valuemax="${session.count}" aria-valuenow="${answered}"><div class="progress-fill" style="width:${answered/session.count*100}%"></div></div>
 <section class="question-card" aria-labelledby="question"><div class="card-top"><span class="label">Powtórka</span><div class="feedback-actions"><button class="icon-btn ${ratings[q.id]==='easy'?'selected':''}" data-rate="easy" aria-pressed="${ratings[q.id]==='easy'}" aria-label="Oznacz jako łatwe" title="To już umiem">${icon('up')}</button><button class="icon-btn negative ${ratings[q.id]==='hard'?'selected':''}" data-rate="hard" aria-pressed="${ratings[q.id]==='hard'}" aria-label="Oznacz do powtórki" title="Chcę to powtórzyć">${icon('down')}</button></div></div>
 <h1 id="question" class="question-title">${esc(q.question)}</h1><p class="answer-label" id="answer-label">Wybierz odpowiedź:</p><div class="answers" role="radiogroup" aria-labelledby="question answer-label">${item.optionIds.map((id,i)=>{const o=q.options.find(o=>o.id===id);return `<button class="answer" role="radio" aria-checked="${item.selectedId===id}" data-answer="${id}"><span class="letter">${'ABCD'[i]}.</span><span>${esc(o.text)}</span><span class="radio" aria-hidden="true"></span></button>`;}).join('')}</div></section>
 <div class="quiz-bottom">${btn(icon('back')+' Wstecz','previous',false,session.index===0?'disabled':'')}<span class="hint"><span class="key">1</span>–<span class="key">4</span> wybierz <span class="key">Enter</span> dalej</span>${btn((session.index===session.count-1?'Zakończ test':'Następne pytanie')+' '+icon('arrow'),'next',true,item.selectedId===null?'disabled':'')}</div><div class="question-meta"><i class="category-dot"></i>${esc(q.category)}<span>Jedna poprawna odpowiedź · Postęp zapisuje się automatycznie</span></div></div>`);
}
function selectAnswer(id){C.answer(session,id,D.questions);storage.write('session',session);renderQuiz();app.querySelector(`[data-answer="${id}"]`)?.focus({preventScroll:true});}
function next(){if(!C.advance(session))return;storage.write('session',session);if(session.finishedAt){history=[structuredClone(session),...history.filter(h=>h.id!==session.id)].slice(0,100);storage.write('history',history);resultSession=session;go('results');}else{renderQuiz();document.getElementById('question').setAttribute('tabindex','-1');document.getElementById('question').focus({preventScroll:true});window.scrollTo({top:0});}}
function renderResults(){
 const s=resultSession;if(!s){go('home');return;}const r=C.score(s,D.questions);
 shell(`<div class="animated"><div class="quiz-top"><button class="text-btn" data-action="home">${icon('back')} Menu główne</button><span>${modeName(s.count)} · ukończony</span></div><section class="result-hero"><div class="eyebrow">Sesja zakończona</div><h1>${r.percent>=80?'Dobra robota!':r.percent>=50?'Wiedza rośnie.':'Każda próba to krok naprzód.'}</h1><p class="muted">${r.percent===100?'Wszystkie odpowiedzi są poprawne. Świetny wynik.':'Sprawdź odpowiedzi i wróć do tego, co wymaga powtórki.'}</p><div class="ring" style="--score:${r.percent}%"><div class="ring-inner"><strong>${r.percent}%</strong><span>poprawnych odpowiedzi</span></div></div><p class="result-score">Twój wynik: <b>${r.correct} / ${r.total}</b></p><div class="stats"><div class="stat"><strong class="green">${r.correct}</strong><span>poprawnych</span></div><div class="stat"><strong class="red">${r.incorrect}</strong><span>niepoprawnych</span></div><div class="stat"><strong>${r.total}</strong><span>odpowiedzi łącznie</span></div></div><div class="actions">${btn(icon('list')+' Przejrzyj błędy ('+r.incorrect+')','mistakes',true)}${btn(icon('repeat')+' Nowy test','retry')}</div><button class="text-btn reveal" data-action="home">Wróć do menu głównego</button></section></div>`);
}
function reviewCard(row,i){const q=row.question;return `<article class="review-card"><span class="eyebrow">${i+1} · ${esc(q.category)}</span><h3>${esc(q.question)}</h3><div class="answer-note bad"><small>Twoja odpowiedź</small>${esc(q.options.find(o=>o.id===row.selectedId)?.text??'Brak odpowiedzi')}</div><div class="answer-note"><small>Poprawna odpowiedź z materiałów</small>${esc(q.options.find(o=>o.id===q.correctOptionId).text)}</div><p class="source">Źródło: ${esc(sourceText(q))}</p></article>`;}
function renderMistakes(){const r=C.score(resultSession,D.questions);shell(`<div class="quiz-wrap animated"><div class="quiz-top"><button class="text-btn" data-action="results">${icon('back')} Wróć do wyniku</button><span>${r.correct} / ${r.total} · ${r.percent}%</span></div><div class="intro"><div class="eyebrow">Ucz się na odpowiedziach</div><h1>Jeszcze jedna powtórka.</h1><p>${r.mistakes.length} pytań, do których warto wrócić.</p></div><div class="review-list">${r.mistakes.length?r.mistakes.map(reviewCard).join(''):`<div class="empty">${icon('check')}<h2>Bez błędów!</h2><p>W tym teście wszystkie odpowiedzi są poprawne.</p></div>`}</div><div class="actions reveal">${btn(icon('repeat')+' Nowy test','retry',true)}${btn('Menu główne','home')}</div></div>`);}
function renderHistory(){shell(`<div class="animated"><div class="intro"><div class="eyebrow">Twój postęp</div><h1>Każda sesja się liczy.</h1><p>Wyniki i odpowiedzi z ostatnich 100 testów w tej przeglądarce.</p></div>${history.length?history.map(s=>{const r=C.score(s,D.questions);return `<article class="history-row"><div class="square-icon">${icon(s.count===10?'bolt':'book')}</div><div class="history-info"><h3>${modeName(s.count)}</h3><p>${new Date(s.finishedAt).toLocaleString('pl-PL',{dateStyle:'medium',timeStyle:'short'})} · ${r.correct} / ${r.total}</p></div><strong class="green">${r.percent}%</strong><button class="text-btn" data-result="${esc(s.id)}" aria-label="Zobacz wynik ${modeName(s.count)}">${icon('arrow')}</button></article>`;}).join(''):`<div class="empty">${icon('clock')}<h2>Tu pojawią się Twoje wyniki.</h2><p>Ukończ pierwszy test, aby zobaczyć postęp.</p><div class="actions reveal">${btn('Rozpocznij szybki test','start-10',true)}</div></div>`}</div>`,'history');}
function bankItems(){const term=query.toLocaleLowerCase('pl');if(bankTab==='issues')return D.issues.filter(i=>(i.reason+' '+i.records.map(r=>r.question+' '+r.answer+' '+r.file).join(' ')).toLocaleLowerCase('pl').includes(term));return D.questions.filter(q=>(bankTab!=='hard'||ratings[q.id]==='hard')&&(!category||q.category===category)&&(q.question+' '+q.options.find(o=>o.id===q.correctOptionId).text).toLocaleLowerCase('pl').includes(term));}
function renderBank(){
 shell(`<div class="animated"><div class="intro"><div class="eyebrow">Materiały w jednym miejscu</div><h1>Baza pytań.</h1><p>${D.meta.sourceRecords} zapisów z ${D.meta.sourceFiles} plików → ${D.questions.length} pytań z podpisami autorów. Powtórzenia są zachowane.</p></div><div class="tabs" aria-label="Widok bazy">${[['ready','Gotowe do nauki'],['hard','Do powtórki'],['issues','Do wyjaśnienia · '+D.meta.reviewGroups]].map(([id,t])=>`<button class="${bankTab===id?'active':''}" data-tab="${id}" aria-pressed="${bankTab===id}">${t}</button>`).join('')}</div>${bankTab==='issues'?`<div class="notice">${icon('info')}<span>${D.meta.reviewRecords} niejednoznacznych zapisów w ${D.meta.reviewGroups} grupach. Zachowano oryginalne odpowiedzi. Te zapisy nie są używane do oceniania testów.</span></div>`:''}<div class="toolbar"><input type="search" id="search" placeholder="Szukaj pytania lub odpowiedzi…" aria-label="Szukaj w bazie" value="${esc(query)}">${bankTab!=='issues'?`<select id="category" aria-label="Kategoria"><option value="">Wszystkie tematy</option>${categories.map(c=>`<option ${category===c?'selected':''}>${esc(c)}</option>`).join('')}</select>`:''}</div><div id="bank-content"></div></div>`,'bank');renderBankContent();
}
function renderBankContent(){const items=bankItems(),size=15,max=Math.max(0,Math.ceil(items.length/size)-1);page=Math.min(page,max);const displayed=items.slice(page*size,(page+1)*size);document.getElementById('bank-content').innerHTML=`<p class="muted" role="status">${items.length} ${bankTab==='issues'?'grup uwag':'pytań'}</p>${displayed.map(q=>bankTab==='issues'?`<details><summary>${esc(q.records[0].question+' ('+q.records[0].author+')')} <span class="muted">· ${q.records.length} zapisów</span></summary><div class="detail-body"><p class="warning">${esc(q.reason)}</p>${q.records.map(r=>`<div class="source-record"><h3>${esc(r.question+' ('+r.author+')')}</h3><p>Odpowiedź w pliku: ${esc(r.answer)}</p><small>${esc(r.file)} · pytanie ${r.number}</small></div>`).join('')}</div></details>`:`<details><summary>${esc(q.question)}</summary><div class="detail-body"><div class="answer-note"><small>Poprawna odpowiedź z materiałów</small>${esc(q.options.find(o=>o.id===q.correctOptionId).text)}</div><p class="source">${esc(q.category)} · Źródło: ${esc(sourceText(q))} · ${q.sources.length} powiązanych zapisów</p><button class="text-btn" data-bank-rate="${q.id}">${ratings[q.id]==='hard'?'Usuń z powtórki':'Oznacz do powtórki'} ${icon('repeat')}</button><details><summary>Zobacz oryginalne zapisy (${q.sources.length})</summary><div class="detail-body">${q.sources.map(id=>{const r=sources.get(id);return `<div class="source-record"><h3>${esc(r.question+' ('+r.author+')')}</h3><p>${esc(r.answer)}</p><small>${esc(r.file)} · pytanie ${r.number}</small></div>`;}).join('')}</div></details></div></details>`).join('')}${!items.length?'<div class="empty">Brak pytań w tym widoku. Zmień wyszukiwanie lub oznacz pytania przyciskiem kciuka w dół podczas testu.</div>':''}${items.length?`<div class="pagination">${btn(icon('back')+' Poprzednia','page-prev',false,page===0?'disabled':'')}<span>${page+1} / ${max+1}</span>${btn('Następna '+icon('arrow'),'page-next',false,page===max?'disabled':'')}</div>`:''}`;}
let toastTimer;function toast(text){document.querySelector('.saved-toast')?.remove();const el=document.createElement('div');el.className='saved-toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),2200);}
app.addEventListener('click',e=>{
 const el=e.target.closest('button');if(!el||el.disabled)return;
 if(el.dataset.answer){selectAnswer(el.dataset.answer);return;}
 if(el.dataset.rate){const id=session.items[session.index].questionId;ratings[id]=ratings[id]===el.dataset.rate?null:el.dataset.rate;storage.write('ratings',ratings);renderQuiz();toast(ratings[id]==='hard'?'Zapisano w „Do powtórki”.':ratings[id]==='easy'?'Oznaczono jako opanowane.':'Oznaczenie usunięte.');return;}
 if(el.dataset.bankRate){const id=el.dataset.bankRate;ratings[id]=ratings[id]==='hard'?null:'hard';storage.write('ratings',ratings);renderBankContent();return;}
 if(el.dataset.category){category=el.dataset.category;query='';page=0;bankTab='ready';go('bank');return;}
 if(el.dataset.tab){bankTab=el.dataset.tab;page=0;go('bank');return;}
 if(el.dataset.result){resultSession=history.find(s=>s.id===el.dataset.result);go('results');return;}
 const a=el.dataset.action;if(!a)return;
 if(a==='odd-start'){startOdd();return;}
 if(a==='odd-resume'){storage.write('active-mode','odd');go('odd');return;}
 if(a==='odd-reveal'||a==='odd-next'||a==='odd-previous'){if(a==='odd-reveal')C.revealReview(oddSession);else if(a==='odd-next')C.advanceReview(oddSession);else oddSession.index=Math.max(0,oddSession.index-1);storage.write('odd-session',oddSession);go('odd');return;}
 if(a==='resume')storage.write('active-mode','quiz');
 if(a.startsWith('start-')){start(Number(a.split('-')[1]));return;}
 if(a==='next')next();else if(a==='previous'){session.index=Math.max(0,session.index-1);storage.write('session',session);renderQuiz();}else if(a==='resume')go('quiz');else if(a==='retry')start(resultSession.count);else if(a==='issues'){bankTab='issues';query='';page=0;go('bank');}else if(a==='page-next'||a==='page-prev'){page+=a==='page-next'?1:-1;renderBankContent();document.getElementById('search').scrollIntoView({block:'start'});}else if(['home','bank','history','results','mistakes'].includes(a)){go(a);}
});
app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;page=0;renderBankContent();}});
app.addEventListener('change',e=>{if(e.target.id==='category'){category=e.target.value;page=0;renderBankContent();}});
document.addEventListener('keydown',e=>{if(screen!=='quiz'||e.altKey||e.ctrlKey||e.metaKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(/^[1-4]$/.test(e.key)){e.preventDefault();selectAnswer(session.items[session.index].optionIds[Number(e.key)-1]);}else if(e.key==='Enter'&&(e.target===document.body||e.target.id==='question'||e.target.id==='main'||e.target.dataset.answer)){e.preventDefault();next();}else if((e.key==='ArrowDown'||e.key==='ArrowUp')&&e.target.dataset.answer){e.preventDefault();const ids=session.items[session.index].optionIds;selectAnswer(ids[(ids.indexOf(e.target.dataset.answer)+(e.key==='ArrowDown'?1:3))%4]);}});
try{C.validate(D.questions);render();}catch(error){app.innerHTML='<main class="shell"><h1>Nie udało się wczytać bazy.</h1><p>Sprawdź plik data/questions.json i ponownie zbuduj bazę.</p></main>';console.error(error);}
