/* Pure quiz rules, shared by the browser and Node tests. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.QuizCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function shuffle(items,rng=Math.random){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function validate(questions){const ids=new Set(),texts=new Set();for(const q of questions){if(ids.has(q.id))throw Error('Duplicate ID '+q.id);ids.add(q.id);const text=q.question.toLocaleLowerCase().replace(/[^\p{L}\p{N}]/gu,'');/* Repeated wording is allowed: source records have distinct IDs. */texts.add(text);if(q.options.length!==4||new Set(q.options.map(o=>o.id)).size!==4||new Set(q.options.map(o=>o.text.toLocaleLowerCase().trim())).size!==4||q.options.filter(o=>o.id===q.correctOptionId).length!==1)throw Error('Invalid choices '+q.id);}return true;}
function createSession(questions,count,rng=Math.random){if(!Number.isInteger(count)||count<1||count>questions.length)throw Error('Invalid question count');const selected=shuffle(questions,rng).slice(0,count);return{id:typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2),count,index:0,startedAt:Date.now(),finishedAt:null,items:selected.map(q=>({questionId:q.id,optionIds:shuffle(q.options,rng).map(o=>o.id),selectedId:null}))};}
function answer(session,optionId,questions){if(session.finishedAt)throw Error('Finished session');const item=session.items[session.index];const q=questions.find(q=>q.id===item.questionId);if(!q||!item.optionIds.includes(optionId))throw Error('Invalid answer');item.selectedId=optionId;return session;}
function advance(session){if(session.finishedAt||!session.items[session.index].selectedId)return false;if(session.index===session.items.length-1)session.finishedAt=Date.now();else session.index++;return true;}
function score(session,questions){const lookup=new Map(questions.map(q=>[q.id,q]));const rows=session.items.map(item=>{const q=lookup.get(item.questionId);return{...item,question:q,correct:!!q&&item.selectedId===q.correctOptionId};});const correct=rows.filter(x=>x.correct).length;return{correct,incorrect:rows.length-correct,total:rows.length,percent:Math.round(100*correct/rows.length),rows,mistakes:rows.filter(x=>!x.correct)};}
function validSession(s,questions){if(!s||![10,40].includes(s.count)||!Array.isArray(s.items)||s.items.length!==s.count||!Number.isInteger(s.index)||s.index<0||s.index>=s.count||typeof s.id!=='string'||!Number.isFinite(s.startedAt)||!(s.finishedAt===null||Number.isFinite(s.finishedAt)))return false;const seen=new Set();return s.items.every((i,n)=>{if(!i||typeof i!=='object')return false;const q=questions.find(q=>q.id===i.questionId);if(!q||seen.has(q.id)||!Array.isArray(i.optionIds)||i.optionIds.length!==4||new Set(i.optionIds).size!==4||!i.optionIds.every(id=>q.options.some(o=>o.id===id))||!(i.selectedId===null||i.optionIds.includes(i.selectedId))||((n<s.index||s.finishedAt)&&i.selectedId===null))return false;seen.add(q.id);return true;});}
return{shuffle,validate,createSession,answer,advance,score,validSession};
});
