'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const C=require('../core.js');const D=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../data/questions.json'),'utf8'));
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
test('all 26 files and all 1038 source pairs are accounted for exactly once',()=>{assert.equal(new Set(D.sources.map(r=>r.file)).size,26);assert.equal(D.sources.length,1038);assert.equal(new Set(D.sources.map(r=>r.id)).size,1038);const covered=[...D.questions.flatMap(q=>q.sources),...D.issues.flatMap(i=>i.records.map(r=>r.id))];assert.equal(covered.length,1038);assert.equal(new Set(covered).size,1038);assert.deepEqual(new Set(covered),new Set(D.sources.map(r=>r.id)));assert.equal(D.meta.readyQuestions+D.meta.mergedRecords+D.meta.reviewRecords,1038);});
test('every playable question has four distinct options, one answer, a category and original source',()=>{C.validate(D.questions);for(const q of D.questions){assert.ok(q.category);assert.ok(q.sources.includes(q.sourceId));const s=D.sources.find(s=>s.id===q.sourceId);assert.equal(s.questionId,q.id);const a=q.options.find(o=>o.id===q.correctOptionId).text;if(!q.editorialNote)assert.equal(a,s.answer.replace(/\s+/g,' ').trim());}});
test('10 and 40 question tests use unique random questions and independently shuffled choices',()=>{for(const n of [10,40]){const a=C.createSession(D.questions,n,rng(51)),b=C.createSession(D.questions,n,rng(213));assert.equal(a.items.length,n);assert.equal(new Set(a.items.map(i=>i.questionId)).size,n);assert.notDeepEqual(a.items.map(i=>i.questionId),b.items.map(i=>i.questionId));const positions=new Set();for(const i of a.items){assert.equal(new Set(i.optionIds).size,4);assert.ok(i.optionIds.includes('correct'));positions.add(i.optionIds.indexOf('correct'));}assert.ok(positions.size>1);assert.ok(C.validSession(a,D.questions));}});
test('perfect, mixed, and zero scores produce exact results and mistake records',()=>{for(const [n,target] of [[10,7],[40,34],[10,0],[40,40]]){const s=C.createSession(D.questions,n,rng(n));for(let i=0;i<n;i++){C.answer(s,i<target?'correct':'d1',D.questions);assert.ok(C.advance(s));}const r=C.score(s,D.questions);assert.equal(r.correct,target);assert.equal(r.incorrect,n-target);assert.equal(r.percent,Math.round(target/n*100));assert.equal(r.mistakes.length,n-target);assert.ok(r.mistakes.every(m=>m.selectedId==='d1'&&m.question.correctOptionId==='correct'));assert.ok(s.finishedAt);assert.ok(C.validSession(JSON.parse(JSON.stringify(s)),D.questions));assert.equal(C.advance(s),false);assert.throws(()=>C.answer(s,'correct',D.questions));}});
test('unanswered question blocks advancement, invalid choices rejected, changed answer affects score',()=>{const s=C.createSession(D.questions,10,rng(7));assert.equal(C.advance(s),false);assert.equal(s.index,0);assert.throws(()=>C.answer(s,'missing',D.questions));C.answer(s,'d1',D.questions);C.answer(s,'correct',D.questions);assert.equal(C.score(s,D.questions).correct,1);C.advance(s);assert.equal(s.index,1);assert.ok(C.validSession(s,D.questions));});
test('corrupt and obsolete saved sessions are rejected',()=>{for(const s of [null,{},[],{count:10}])assert.equal(C.validSession(s,D.questions),false);const s=C.createSession(D.questions,10);s.items[1].questionId=s.items[0].questionId;assert.equal(C.validSession(s,D.questions),false);const b=C.createSession(D.questions,40);b.index=39;assert.equal(C.validSession(b,D.questions),false);});

test('null saved item is rejected without crashing startup',()=>{const s=C.createSession(D.questions,10);s.items[0]=null;assert.equal(C.validSession(s,D.questions),false);});
test('disputed mode samples only original flagged records and preserves source answers',()=>{const records=C.reviewRecords(D.issues);assert.equal(records.length,134);const a=C.createReviewSession(D.issues,10,rng(18)),b=C.createReviewSession(D.issues,10,rng(67));assert.ok(C.validReviewSession(a,D.issues));assert.equal(new Set(a.ids).size,10);assert.notDeepEqual(a.ids,b.ids);const normalSources=new Set(D.questions.map(q=>q.sourceId));for(const r of records){assert.ok(!normalSources.has(r.id));assert.equal(r.answer,D.sources.find(x=>x.id===r.id).answer);assert.ok(r.reason);assert.ok(r.author);}});
test('disputed cards require reveal, resume correctly and finish after all ten',()=>{const s=C.createReviewSession(D.issues,10,rng(9));assert.equal(C.advanceReview(s),false);for(let n=0;n<10;n++){assert.equal(s.index,n);C.revealReview(s);C.revealReview(s);assert.equal(s.seen.length,n+1);assert.ok(C.validReviewSession(JSON.parse(JSON.stringify(s)),D.issues));assert.equal(C.advanceReview(s),true);}assert.ok(s.finished);assert.ok(C.validReviewSession(s,D.issues));assert.equal(C.advanceReview(s),false);for(const invalid of [null,{}, {...s,ids:[...s.ids.slice(1),s.ids[1]]},{...s,seen:[]},{...s,index:10}])assert.equal(C.validReviewSession(invalid,D.issues),false);});
test('answer snapshots preserve review text when the database is edited later',()=>{const s=C.createSession(D.questions,10,rng(91));C.answer(s,'d1',D.questions);const q=D.questions.find(q=>q.id===s.items[0].questionId),before=q.options.find(o=>o.id==='d1').text;const edited=D.questions.map(x=>x.id===q.id?{...x,options:x.options.map(o=>o.id==='d1'?{...o,text:'Updated distractor'}:o)}:x);assert.equal(C.score(s,edited).rows[0].question.options.find(o=>o.id==='d1').text,before);});
test('editorial update changes distractors but keeps every source answer key',()=>{assert.equal(D.meta.distractorRevision,3);assert.equal(D.meta.refinedQuestions,748);for(const q of D.questions.filter(q=>q.legacyOptions)){assert.deepEqual(q.options.find(o=>o.id===q.correctOptionId),q.legacyOptions.find(o=>o.id===q.correctOptionId));assert.ok(q.options.slice(1).every(o=>!/^Wyłącznie /i.test(o.text)));}});
test('all 904 playable source occurrences keep their author and repeated wording is allowed',()=>{assert.equal(D.questions.length,904);for(const q of D.questions){const s=D.sources.find(s=>s.id===q.sourceId);assert.equal(q.author,s.author);assert.ok(q.question.endsWith(' ('+s.author+')'));assert.equal(q.sources.length,1);}assert.equal(new Set(D.sources.map(s=>s.author)).size,26);assert.equal(D.sources.find(s=>s.file==='PatrykWitczak.docx').author,'Patryk Witczak');assert.equal(D.sources.find(s=>s.file==='Marcel-Pawlak.docx.docx').author,'Marcel Pawlak');const q=D.questions[0];assert.equal(C.validate([q,{...q,id:'another-source-record'}]),true);});
